### PR TITLE
Merge the two SW360UpdaterTest classes together

### LINKED ISSUE #593: SW360UpdaterTest#testIllegalStateIsCaught does not do anything
In Compliance Tool, we have a test classe `SW360UpdaterTest`: Most of the tests of this class are trivial except `testIllegalStateIsCaught()`.
As I understand it, it should check if an exception is caught. The exception should be thrown through mocking in `SW360Updater#uploadReleaseWithClearingDocumentFromArtifact`.

However, **and this is the bug**, this method is never called : the artefacts collection in `SW360Updater` at the line  `artifacts.forEach(this::uploadReleaseWithClearingDocumentFromArtifact);` is empty.

I believe this all come down to the fact that the CSV created by the test is empty.

### PR DESCRIPTION
**Pull request by nnobelis**
SW360UpdaterTestWithFailure was made with #575 to test the new exception handling.
However it turned out that SW360UpdaterTest was doing the same test, but wrongly
on an empty file.
Thus we can consolidate the two tests in one and make it run on a file with two entries.

Closes #593

Signed-off-by: Nicolas Nobelis <nicolas.nobelis@bosch.io>

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to? (*Refer to issue here*)
#593 
> * How is it solving the issue?
We merge the incriminated test with the new one from last PR.

> * Did you add or update any new dependencies that are required for your change?
no

@neubs-bsi 
@oheger-bosch 

bug fix

*Type of change*:  

### Checklist
Must:
- [x] All related issues are referenced in commit messages

### CODE REVIEW

File: assembly/compliance-tool/src/test/java/org/eclipse/sw360/antenna/frontend/compliancetool/sw360/updater/SW360UpdaterTest.java [hunk 1]
```diff
@@ -70,20 +78,28 @@ public void testIllegalStateIsCaught() throws IOException {
...
         final ClearingReportGenerator clearingReportGenerator = mock(ClearingReportGenerator.class);
         when(clearingReportGenerator.createClearingDocument(any(), any()))
-                .thenThrow(new SW360ClientException("Clearing doc generation error"));
+                .thenThrow(new SW360ClientException("Clearing doc generation error"))
+                .thenReturn(folder.newFile("clearing_document.test").toPath());
         SW360Updater updater = new SW360Updater(updaterImpl, configurationMock, clearingReportGenerator);
-        updater.execute();
 
-        verify(releaseClientAdapter, never()).uploadAttachments(any());
+        // and ans exception is nevertheless thrown by SW360ReleaseClientAdapterAsyncImpl
```
Comment (oheger-bosch) [inline assembly/compliance-tool/src/test/java/org/eclipse/sw360/antenna/frontend/compliancetool/sw360/updater/SW360UpdaterTest.java:90]: typo: and *an* exception is ...

**Review by oheger-bosch — APPROVED** [review]
Except for a small typo in a comment, everything is fine with me.

File: assembly/compliance-tool/src/test/java/org/eclipse/sw360/antenna/frontend/compliancetool/sw360/updater/SW360UpdaterTest.java (hunk 1 above)
Comment (nnobelis) [reply assembly/compliance-tool/src/test/java/org/eclipse/sw360/antenna/frontend/compliancetool/sw360/updater/SW360UpdaterTest.java]: done

**Review by neubs-bsi — APPROVED** [review]
